name = 'api'
main = 'src/index.ts'
compatibility_date = '2024-03-05'

[[d1_databases]]
binding = 'DB'
database_name = 'softhub_db'
database_id = '631a8b23-4a75-4e59-8b73-61af4b07d5f7'

[[kv_namespaces]]
binding = "softhub_kv"
id = "148fcf4fa8464a24b5f8f038ee1657f3"

[ai]
binding = "AI"

[triggers]
crons = ["45 16 * * *", "59 23 * * *", "0 3 * * 0"]

[vars]
APP_ENV = "production"
BOOTSTRAP_ADMIN_EMAIL = "mateus099803@unieuro.com.br"